[tasks.lint]
command = "cargo"
args = ["clippy"]
dependencies = [
    "check:fmt",
    "check:sort",
    "lint:rusoto",
    "lint:rusoto_rustls",
    "lint:awssdk",
]

[tasks."lint:rusoto"]
command = "cargo"
args = ["clippy", "--no-default-features", "--features", "rusoto"]

[tasks."lint:rusoto_rustls"]
command = "cargo"
args = ["clippy", "--no-default-features", "--features", "rusoto_rustls"]

[tasks."lint:awssdk"]
command = "cargo"
args = ["clippy", "--no-default-features", "--features", "awssdk"]

[tasks."check:fmt"]
description = "Check format"
command = "cargo"
args = ["fmt", "--check"]

[tasks."check:sort"]
description = "Check if Cargo.toml dependencies sorted"
install_crate = { crate_name = "cargo-sort" }
command = "cargo"
args = ["sort", "--check"]

[tasks.test]
description = "Run nextest"
install_crate = { crate_name = "cargo-nextest" }
command = "cargo"
args = ["nextest", "run"]
dependencies = ["test:rusoto", "test:rusoto_rustls", "test:awssdk"]

[tasks."test:rusoto"]
command = "cargo"
args = ["nextest", "run", "--no-default-features", "--features", "rusoto"]

[tasks."test:rusoto_rustls"]
command = "cargo"
args = [
    "nextest",
    "run",
    "--no-default-features",
    "--features",
    "rusoto_rustls",
]

[tasks."test:awssdk"]
command = "cargo"
args = ["nextest", "run", "--no-default-features", "--features", "awssdk"]
